apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quarkus-ms
  namespace: quarkus-ms
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: quarkus-ms.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quarkus-ms
                port:
                  number: 80
